#!/bin/sh

#
# Hive 5
#
# Build dependencies for macOS
#

check_command(){
    command -v "$1" >/dev/null 2>&1 || { echo "[!] Cannot build dependencies: missing command. Aborting..." >&2; exit 1; }
}

check_command brew
check_command carthage
check_command swift

echo "[*] Building dependencies for Hive5..."

brew install libressl
carthage bootstrap
swift package generate-xcodeproj

